import { Model } from '@vuex-orm/core';
import { ORMDatabase } from './database';

/**
 * Creates an vuex-orm Model
 * @param entityName The name of the entity to be used as the key for the state
 */
export function OrmModel(entityName: string, parentEntity?: string, types?: { [key: string]: typeof Model }, typeKey?: string) {
    return function <Model extends Function>(constructor: Model): Model | void {
        const model: Function = constructor;

        // Set the entity name on the model constructor
        (model as any).entity = entityName;

        // Set the parent entity name on the model constructo (if present)
        if (parentEntity) { (model as any).baseEntity = parentEntity; }

        // Setup the types and descriminator (if set)
        if (types) { (model as any).types = () => types; }
        if (types && typeKey) { (model as any).typeKey = typeKey; }

        // Add the fields generated by tha attribute decorators
        (model as any).fields = () => (model as any)._fields || {};

        // Register the entity in the database
        ORMDatabase.registerEntity(model as unknown as typeof Model);

        return constructor;
    };
}